name: omega bone
favicon: null
layout_spectrum: 0.06644093617796898
typography_spectrum: 0.27167862420901656
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.19839801476337016
  lightness: 0.3434870224446058
  saturation: 0.380248986184597
  rhythmicContrast: 0.10734825837425888
purpose: []
